/**
 * Bye Bye Google AI parity — No AI Extension
 * Hides AI Overviews + optionally Ads, Shopping, Discussions, Videos, PAA, etc.
 * Strategy: CSS instant hide + text-matching (16 languages) + block walking (MjjYud/g) + udm=14 server-side fallback.
 * Based on: Bye Bye Google AI (PCWorld/Tom's Hardware) behavior + our complete blocking (udm=14)
 */
(() => {
  const STORAGE_DEFAULTS = {
    enabled: true,
    blockOverview: true, // default ON — like Bye Bye
    blockAiMode: true,
    stripUdm50: true,
    webOnly: false, // off by default like Bye Bye (turn on for COMPLETE server-side block)
    aggressive: false,
    // Bye Bye parity toggles — all OFF by default
    hideAds: false,
    hideShopping: false,
    hideDiscussions: false,
    hideVideos: false,
    hidePAA: false, // People Also Ask / Related questions
    hideWhatPeopleSaying: false,
    blockedCount: 0
  };

  let config = { ...STORAGE_DEFAULTS };
  let observer = null;
  let runQueued = false;

  chrome.storage.sync.get(STORAGE_DEFAULTS, d => { config = d; if (config.enabled) boot(); });
  chrome.storage.onChanged.addListener((changes, area) => {
    if (area !== 'sync') return;
    let needsReboot = false;
    for (const k of Object.keys(changes)) {
      config[k] = changes[k].newValue;
      if (['enabled','blockOverview','blockAiMode','aggressive','hideAds','hideShopping','hideDiscussions','hideVideos','hidePAA','hideWhatPeopleSaying'].includes(k)) needsReboot = true;
    }
    if (needsReboot) {
      if (config.enabled) { boot(); scanAll(); }
      else { teardown(); document.querySelectorAll('.no-ai-hidden').forEach(e=>e.classList.remove('no-ai-hidden')); }
    }
    if (changes.webOnly || changes.stripUdm50) handleUrlParams();
  });

  function boot() {
    if (observer) return;
    handleUrlParams();
    scanAll();
    observer = new MutationObserver(() => {
      if (runQueued) return;
      runQueued = true;
      requestAnimationFrame(() => { runQueued=false; scanAll(); });
    });
    observer.observe(document.documentElement, { childList:true, subtree:true });
    let lastUrl = location.href;
    setInterval(()=>{ if(location.href!==lastUrl){ lastUrl=location.href; handleUrlParams(); scanAll(); } },500);
  }
  function teardown(){ if(observer){ observer.disconnect(); observer=null; } }

  function handleUrlParams(){
    const url = new URL(location.href);
    if (!url.hostname.includes('google')) return;
    if (config.stripUdm50 && url.searchParams.get('udm')==='50'){ url.searchParams.delete('udm'); history.replaceState(null,'',url.toString()); }
    if (config.webOnly && url.pathname==='/search' && url.searchParams.get('udm')!=='14' && url.searchParams.has('q')){
      url.searchParams.set('udm','14');
      location.replace(url.toString());
    }
  }

  // 16 languages — like Bye Bye v1.4
  const AI_OVERVIEW_RE = /(AI\s*Overview|KI[-\s]*Übersicht|Vue d'ensemble par l'IA|Aperçu par l'IA|Visão geral (da |com )?IA|Resumen de IA|Panoramica (sull'|con )?IA|AIによる概要|AI\s*overblik|AI-overzicht|AI\s*Översikt|Przegląd AI|Обзор от ИИ)/i;
  const AI_MODE_RE = /^\s*AI\s*Mode\s*$/i;
  const AI_MODE_ALT_RE = /(KI-Modus|Mode IA|Modo IA|Modalità AI)/i;
  const GENERATIVE_RE = /(Generative AI|AI-generated|Generated by AI|Créé par IA|Erstellt mit KI)/i;

  // Bye Bye block headings (16 languages)
  const ADS_RE = /^\s*Sponsored\s*$/i;
  const SPONSORED_FOOTER_RE = /Sponsored|Annonce|Anzeige|Patrocinado|Gesponsert/i;
  const SHOPPING_RE = /^\s*(Shopping|Shopping results|Products|Anzeigen \u00b7 Shopping|Sponsored \u00b7 Shopping)\s*$/i;
  const DISCUSSIONS_RE = /^\s*(Discussions and forums|Discussions|Forums|Discussions et forums|Diskussionen und Foren|Discusiones y foros|Discussioni e forum)\s*$/i;
  const VIDEOS_RE = /^\s*(Videos|Short videos|Vidéos|Vídeos|Video|Kurze Videos)\s*$/i;
  const PAA_RE = /^\s*(People also ask|Related questions|People also search for|Autres questions posées|Nutzer fragen auch|Preguntas relacionadas|Altre domande|Perguntas relacionadas|Related searches|Recherches associées)\s*$/i;
  const WHAT_PEOPLE_SAYING_RE = /^\s*What people are saying\s*$/i;

  function isVisible(el){ const r=el.getBoundingClientRect(); return r.width>0 || r.height>0; }
  function findBlockContainer(startEl){
    let el=startEl;
    for(let i=0;i<10&&el&&el!==document.body;i++){
      if(el.matches && (
        el.matches('div.MjjYud')||el.matches('div.g')||el.matches('div[data-hveid]')||el.matches('div.ULSxyf')||el.matches('div[data-subtree]')||el.matches('div[data-ved][data-hveid]')||el.matches('div#search > div')
      )){
        if(el.id!=='search'&&el.id!=='rso'&&el.id!=='tads') return el;
      }
      el=el.parentElement;
    }
    return startEl.parentElement?.parentElement?.parentElement||startEl;
  }
  function hide(el, reason){
    if(!el||el.classList.contains('no-ai-hidden')) return;
    el.classList.add('no-ai-hidden');
    el.setAttribute('data-no-ai-reason',reason);
    config.blockedCount++; chrome.storage.sync.set({blockedCount:config.blockedCount});
  }

  function scanAll(){
    if(!config.enabled) return;

    // 1) Attribute fast path — AI Overview
    if(config.blockOverview){
      document.querySelectorAll('div[data-attrid*="AIOverview" i], div[data-subtree*="ai_overview" i]').forEach(e=>hide(findBlockContainer(e),'attr-ai'));
    }

    // 2) Text scan — AI Overview + footer heuristic (photosynthesis fix)
    if(config.blockOverview){
      const footerRE = /AI responses may include|Generative AI is experimental|Learn more|Show more|Show less/i;
      const cands = document.querySelectorAll('h1,h2,h3,span,div,a,p,[role="heading"],[data-attrid],[data-hveid]');
      for(const el of cands){
        if(el.classList.contains('no-ai-hidden')) continue;
        const t=(el.textContent||'').trim();
        if(t.length>3 && t.length<120 && (AI_OVERVIEW_RE.test(t) || (footerRE.test(t) && el.closest('#search,#rso')))){
          const root=document.getElementById('search')||document.getElementById('rso')||document.body;
          if(!root.contains(el)) continue;
          const block=findBlockContainer(el);
          if(block && isVisible(block)) hide(block,'ai-overview:'+t.slice(0,30));
        }
      }
    }

    // 3) AI Mode
    if(config.blockAiMode){
      document.querySelectorAll('a[href*="udm=50"]').forEach(a=>{
        const tab=a.closest('div[role="navigation"] div, div[role="listitem"], li, div.hdtb-mitem')||a;
        hide(tab,'ai-mode-link'); a.classList.add('no-ai-hidden');
      });
      const nav=document.querySelector('div[role="navigation"]'); const scope=nav||document;
      scope.querySelectorAll('a,span,div[role="tab"]').forEach(el=>{
        const t=(el.textContent||'').trim();
        if((AI_MODE_RE.test(t)||AI_MODE_ALT_RE.test(t))&&t.length<30) hide(el.closest('a,div[role="tab"],li')||el,'ai-mode-text');
      });
    }

    // 4) Bye Bye parity — each block by heading
    const searchRoot=document.getElementById('search')||document.body;

    if(config.hideAds){
      // attribute based
      document.querySelectorAll('div[data-text-ad], div#tads, div#tvcap, div[data-ved][data-hveid]').forEach(el=>{
        // check if contains Sponsored label
        const hasSponsored = el.textContent && ADS_RE.test(el.querySelector('span')?.textContent||'') || SPONSORED_FOOTER_RE.test(el.textContent.slice(0,300));
        if(el.id==='tads' || el.id==='tvcap' || el.hasAttribute('data-text-ad') || hasSponsored){
          if(searchRoot.contains(el) && isVisible(el)) hide(el,'ads');
        }
      });
      // span Sponsored heading
      document.querySelectorAll('span').forEach(el=>{
        const t=(el.textContent||'').trim();
        if(ADS_RE.test(t) && el.closest('#search,#tads,#tvcap')){
          hide(findBlockContainer(el),'ads-text');
        }
      });
    }

    if(config.hideShopping){
      document.querySelectorAll('h2,h3,span,div').forEach(el=>{
        const t=(el.textContent||'').trim();
        if(t.length<40 && SHOPPING_RE.test(t) && el.closest('#search')){
          hide(findBlockContainer(el),'shopping');
        }
      });
    }

    if(config.hideDiscussions){
      document.querySelectorAll('h2,h3,span,div[role="heading"]').forEach(el=>{
        const t=(el.textContent||'').trim();
        if(t.length<50 && DISCUSSIONS_RE.test(t) && el.closest('#search')){
          hide(findBlockContainer(el),'discussions');
        }
      });
    }

    if(config.hideVideos){
      document.querySelectorAll('h2,h3,span').forEach(el=>{
        const t=(el.textContent||'').trim();
        if(t.length<30 && VIDEOS_RE.test(t) && el.closest('#search')){
          // Videos block is often a g-scrolling-carousel; hide the whole block
          hide(findBlockContainer(el),'videos');
        }
      });
      // fallback: hide carousel with video thumbnails if heading found
      if(document.querySelector('h3')?.textContent?.match(VIDEOS_RE)){
        document.querySelectorAll('g-scrolling-carousel, div[data-hveid][data-ved]').forEach(el=>{
          if(el.closest('#search') && el.querySelector('video, img[src*="video"]')) hide(el,'videos-carousel');
        });
      }
    }

    if(config.hidePAA){
      document.querySelectorAll('h2,h3,span,div').forEach(el=>{
        const t=(el.textContent||'').trim();
        if(t.length<50 && PAA_RE.test(t) && el.closest('#search')){
          hide(findBlockContainer(el),'paa');
        }
      });
    }

    if(config.hideWhatPeopleSaying){
      document.querySelectorAll('h2,h3,span').forEach(el=>{
        const t=(el.textContent||'').trim();
        if(WHAT_PEOPLE_SAYING_RE.test(t) && el.closest('#search')){
          hide(findBlockContainer(el),'what-people-saying');
        }
      });
    }

    // Aggressive legacy
    if(config.aggressive){
      document.querySelectorAll('span,div').forEach(el=>{
        const t=(el.textContent||'').trim();
        if(t.length<80 && GENERATIVE_RE.test(t) && el.matches('span,div') && t.length<40){
          const badge=el.closest('div.MjjYud, div.g, span')||el;
          if(badge && badge.textContent.trim().length<120) hide(badge,'aggressive:'+t.slice(0,30));
        }
      });
    }
  }

  window.__noAi={scanAll, findBlockContainer, get config(){return config;}};
})();
