/**
 * No AI — Block Google AI Overviews & AI Content
 * Strategy: CSS hides instantly, JS MutationObserver catches everything Google streams in.
 * - Walks up to the search result block boundary (MjjYud / g / ULSxyf etc.) so entire module disappears cleanly.
 * - Text-matching in multiple languages (EN, DE, FR, PT, ES, IT, JA...)
 * - Handles AI Overview, AI Mode tab, AI Mode pill, Gemini prompts, and aggressive AI badges.
 */
(() => {
  const STORAGE_DEFAULTS = {
    enabled: true,
    blockOverview: true,
    blockAiMode: true,
    stripUdm50: true,
    webOnly: false, // udm=14
    aggressive: false, // higher note: block all AI content
    blockedCount: 0
  };

  let config = { ...STORAGE_DEFAULTS };
  let observer = null;
  let runQueued = false;

  // Load config
  chrome.storage.sync.get(STORAGE_DEFAULTS, (data) => {
    config = data;
    if (config.enabled) boot();
  });

  chrome.storage.onChanged.addListener((changes, area) => {
    if (area !== 'sync') return;
    let needsReboot = false;
    for (const k of Object.keys(changes)) {
      config[k] = changes[k].newValue;
      if (['enabled', 'blockOverview', 'blockAiMode', 'aggressive'].includes(k)) needsReboot = true;
    }
    if (needsReboot) {
      if (config.enabled) {
        boot();
        scanAll();
      } else {
        teardown();
        // reveal hidden elements if disabled
        document.querySelectorAll('.no-ai-hidden').forEach(el => el.classList.remove('no-ai-hidden'));
      }
    }
    // Handle udm redirects immediately
    if (changes.webOnly || changes.stripUdm50) handleUrlParams();
  });

  function boot() {
    if (observer) return;
    handleUrlParams();
    scanAll();
    observer = new MutationObserver(() => {
      if (runQueued) return;
      runQueued = true;
      requestAnimationFrame(() => {
        runQueued = false;
        scanAll();
      });
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
    // also watch for SPA navigation (Google uses pushState)
    let lastUrl = location.href;
    setInterval(() => {
      if (location.href !== lastUrl) {
        lastUrl = location.href;
        handleUrlParams();
        scanAll();
      }
    }, 500);
  }

  function teardown() {
    if (observer) {
      observer.disconnect();
      observer = null;
    }
  }

  function handleUrlParams() {
    const url = new URL(location.href);
    if (!url.hostname.includes('google')) return;

    // Strip udm=50 (AI Mode) -> back to regular search
    if (config.stripUdm50 && url.searchParams.get('udm') === '50') {
      url.searchParams.delete('udm');
      history.replaceState(null, '', url.toString());
      // optionally reload is not needed — Google will re-render
    }

    // Web-only mode udm=14
    if (config.webOnly && url.pathname === '/search' && url.searchParams.get('udm') !== '14' && url.searchParams.has('q')) {
      url.searchParams.set('udm', '14');
      // Avoid infinite loop: only if not already 14
      location.replace(url.toString());
    }
  }

  // --- Detection helpers ---

  // All languages we catch (Google localizes the heading)
  const AI_OVERVIEW_RE = /(AI\s*Overview|KI[-\s]*Übersicht|Vue d'ensemble par l'IA|Aperçu par l'IA|Visão geral (da |com )?IA|Resumen de IA|Panoramica (sull'|con )?IA|AIによる概要|AI\s*overblik|AI-overzicht)/i;
  const AI_MODE_RE = /^\s*AI\s*Mode\s*$/i;
  const AI_MODE_ALT_RE = /(KI-Modus|Mode IA|Modo IA|Modalità AI)/i;

  const GENERATIVE_RE = /(Generative AI|AI-generated|Generated by AI|Créé par IA|Erstellt mit KI|AI summary|Résumé IA)/i;

  function isVisible(el) {
    const r = el.getBoundingClientRect();
    return r.width > 0 || r.height > 0;
  }

  // Walk up to the block container Google uses for a single result module
  function findBlockContainer(startEl) {
    let el = startEl;
    // Google wraps each SERP module in div with e.g. class="MjjYud" or "g" or data-hveid
    // We walk up until we hit a container that looks like a block but not the whole #search
    for (let i = 0; i < 8 && el && el !== document.body; i++) {
      if (el.matches && (
        el.matches('div.MjjYud') ||
        el.matches('div.g') ||
        el.matches('div[data-hveid]') ||
        el.matches('div.ULSxyf') ||
        el.matches('div[data-subtree]') ||
        el.matches('div#search > div') // fallback
      )) {
        // Ensure it's not the entire search container
        if (el.id !== 'search' && el.id !== 'rso') return el;
      }
      el = el.parentElement;
    }
    // fallback: hide the header's parent (3 levels up)
    return startEl.parentElement?.parentElement?.parentElement || startEl;
  }

  function hide(el, reason) {
    if (!el || el.classList.contains('no-ai-hidden')) return;
    el.classList.add('no-ai-hidden');
    el.setAttribute('data-no-ai-reason', reason);
    config.blockedCount++;
    chrome.storage.sync.set({ blockedCount: config.blockedCount });
    // debug
    // console.log('[No AI] hid', reason, el);
  }

  function scanAll() {
    if (!config.enabled) return;

    // 1) AI Overview — by attribute (fast)
    if (config.blockOverview) {
      document.querySelectorAll('div[data-attrid*="AIOverview" i], div[data-subtree*="ai_overview" i]').forEach(el => {
        const block = findBlockContainer(el);
        hide(block, 'attr-ai-overview');
      });
    }

    // 2) AI Overview — by text scan (robust against rotation) — photosynthesis hotfix 2026-09-23
    if (config.blockOverview) {
      const footerRE = /AI responses may include|Generative AI is experimental|Learn more|Show more|Show less/i;
      const candidates = document.querySelectorAll('h1, h2, h3, span, div, a, p, [role="heading"], [data-attrid], [data-hveid]');
      for (const el of candidates) {
        if (el.classList.contains('no-ai-hidden')) continue;
        const t = (el.textContent || '').trim();
        // catch header OR footer (footer is reliable when header rotates)
        if (t.length > 3 && t.length < 120 && (AI_OVERVIEW_RE.test(t) || (footerRE.test(t) && el.closest('#search, #rso')))) {
          // Ensure it's inside search, not random page mention
          const searchRoot = document.getElementById('search') || document.getElementById('rso') || document.body;
          if (!searchRoot.contains(el)) continue;
          const block = findBlockContainer(el);
          // Sanity: block should be sizable and near top
          if (block && isVisible(block)) {
            hide(block, 'text-ai-overview:' + t.slice(0, 30));
          }
        }
      }
    }

    // 3) AI Mode — tab in SERP nav + pill on homepage
    if (config.blockAiMode) {
      // Hide any link to udm=50 (AI Mode)
      document.querySelectorAll('a[href*="udm=50"]').forEach(a => {
        // Hide the tab, not just the anchor — walk to tab element
        const tab = a.closest('div[role="navigation"] div, div[role="listitem"], li, div.hdtb-mitem') || a;
        hide(tab, 'ai-mode-link');
        // Also hide the anchor itself
        a.classList.add('no-ai-hidden');
      });

      // Text-match tabs that say "AI Mode" (and localized variants)
      const nav = document.querySelector('div[role="navigation"]');
      const scope = nav || document;
      scope.querySelectorAll('a, span, div[role="tab"]').forEach(el => {
        const t = (el.textContent || '').trim();
        if ((AI_MODE_RE.test(t) || AI_MODE_ALT_RE.test(t)) && t.length < 30) {
          const tab = el.closest('a, div[role="tab"], li') || el;
          // Extra check: near other tabs
          if (tab) hide(tab, 'ai-mode-text:' + t);
        }
      });

      // Homepage AI Mode pill inside the search bar
      document.querySelectorAll('button, a, div[jsname]').forEach(el => {
        const t = (el.textContent || '').trim();
        if (t.length < 20 && AI_MODE_RE.test(t)) {
          // Only hide if it's inside the search homepage
          if (el.closest('div[jsname="uFMOof"], form[role="search"], div.A8SBwf')) {
            hide(el.closest('button, a') || el, 'ai-mode-pill');
          }
        }
      });
    }

    // 4) Aggressive — broader AI content (higher note)
    if (config.aggressive) {
      // Google AI features: Gemini, Labs, AI expand, Generative AI disclaimers
      document.querySelectorAll('span, div, a, button').forEach(el => {
        const t = (el.textContent || '').trim();
        if (t.length < 80 && GENERATIVE_RE.test(t)) {
          // Only hide small disclaimers/badges, not entire articles that mention AI
          // We hide the badge container, not paragraphs
          if (el.matches('span, div') && t.length < 40) {
            const badge = el.closest('div.MjjYud, div.g, span') || el;
            // Avoid hiding organic results that just mention AI in text — check if it's a small UI badge
            if (badge && badge.textContent.trim().length < 120) {
              // Check visual cues: often has icon + short label
              hide(badge, 'aggressive-badge:' + t.slice(0, 30));
            }
          }
        }
      });

      // Hide "AI Images", "AI-generated images" sections in image search
      document.querySelectorAll('div, span').forEach(el => {
        const t = (el.textContent || '').trim();
        if (/AI-?generated images/i.test(t) && t.length < 50) {
          const block = findBlockContainer(el);
          hide(block, 'aggressive-ai-images');
        }
      });

      // YouTube AI summaries / Gemini in Workspace (if on google domains)
      document.querySelectorAll('[aria-label*="Gemini" i], [aria-label*="Ask Gemini" i], button:has(span:contains("Gemini"))').forEach(el => {
        // fallback without :contains — use text check above already
      });

      // Generic — hide fixed Gemini prompts on google.com
      document.querySelectorAll('div[jsname][data-ved]').forEach(el => {
        // heuristic: if it contains Gemini icon + prompt text, hide
        if (el.textContent.includes('Gemini') && el.textContent.length < 200) {
          // Only if inside SERP header
          if (el.closest('#search')) {
            // be conservative
          }
        }
      });
    }
  }

  // Expose for debugging
  window.__noAi = { scanAll, findBlockContainer, get config() { return config; } };
})();
